# Generated by Django 6.0.3 on 2026-04-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('distancia_km', models.DecimalField(decimal_places=1, max_digits=4)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='livrarias/')),
                ('status_aberto', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('capa', models.ImageField(upload_to='capas/')),
                ('preco_aluguel', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
