# Generated by Django 6.0.3 on 2026-04-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gekkoteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Coleção')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='colecoes/', verbose_name='Imagem do Banner')),
                ('ativa', models.BooleanField(default=True, verbose_name='Mostrar na Home?')),
            ],
            options={
                'verbose_name': 'Coleção',
                'verbose_name_plural': 'Coleções',
            },
        ),
    ]
